/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "rgba(255, 255, 255, 0.1)",
        input: "rgba(255, 255, 255, 0.1)",
        ring: "#3D81CC",
        background: "#000000",
        foreground: "#ffffff",
        primary: {
          DEFAULT: "#3D81CC",
          foreground: "#ffffff",
        },
        secondary: {
          DEFAULT: "#ffffff",
          foreground: "#000000",
        },
        accent: {
          DEFAULT: "#3D81CC",
          foreground: "#ffffff",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "rgba(255, 255, 255, 0.1)",
          foreground: "rgba(255, 255, 255, 0.6)",
        },
        popover: {
          DEFAULT: "#000000",
          foreground: "#ffffff",
        },
        card: {
          DEFAULT: "#000000",
          foreground: "#ffffff",
        },
        "primary-fixed": "#3D81CC",
        "on-tertiary": "#000000",
        "tertiary-fixed-dim": "#a1a1aa",
        "on-primary-container": "#ffffff",
        "on-secondary": "#000000",
        "on-background": "#ffffff",
        "secondary-container": "rgba(255, 255, 255, 0.1)",
        "inverse-primary": "#3D81CC",
        "surface-container-high": "#1a1a1a",
        "primary-container": "#3D81CC",
        "error-container": "#ff0000",
        "on-surface-variant": "rgba(255, 255, 255, 0.7)",
        "on-primary": "#ffffff",
        "on-secondary-container": "#ffffff",
        "primary-fixed-dim": "#3D81CC",
        "surface-container-low": "#0a0a0a",
        "on-error-container": "#ffffff",
        "surface": "#000000",
        "surface-dim": "#0a0a0a",
        "on-primary-fixed-variant": "#ffffff",
        "error": "#ff0000",
        "surface-container-highest": "rgba(255, 255, 255, 0.1)",
        "tertiary": "#a1a1aa",
        "inverse-on-surface": "#000000",
        "outline": "rgba(255, 255, 255, 0.1)",
        "on-surface": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed": "#ffffff",
        "surface-variant": "#111111",
        "surface-tint": "#3D81CC",
        "tertiary-container": "rgba(255, 255, 255, 0.1)",
        "secondary-fixed-dim": "#e4e4e7",
        "on-tertiary-fixed": "#000000",
        "secondary-fixed": "#ffffff",
        "outline-variant": "rgba(255, 255, 255, 0.2)",
        "surface-bright": "#1a1a1a",
        "on-secondary-fixed": "#000000",
        "tertiary-fixed": "#e4e4e7",
        "inverse-surface": "#ffffff",
        "surface-container": "#111111",
        "surface-container-lowest": "#000000",
        "on-tertiary-fixed-variant": "#000000",
        "on-secondary-fixed-variant": "#000000",
        "on-tertiary-container": "#ffffff"
      },
      fontFamily: {
        ans: ["Space Grotesk", "sans-serif"],
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Space Grotesk", "sans-serif"],
        label: ["JetBrains Mono", "monospace"],
        mono: ["JetBrains Mono", "monospace"],
        sans: ["Space Grotesk", "sans-serif"],
        serif: ["Space Grotesk", "sans-serif"]
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
