/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ConversationsMyRouteImport } from './routes/conversations/my'
import { Route as ChatConversationIdRouteImport } from './routes/chat/$conversationId'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'
import { Route as ChatNewAgentIdRouteImport } from './routes/chat/new/$agentId'
import { Route as AuthResetPasswordTokenRouteImport } from './routes/auth/reset-password/$token'
import { Route as AdminFeedbackFeedbackIdRouteImport } from './routes/admin/feedback/$feedbackId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsMyRoute = ConversationsMyRouteImport.update({
  id: '/conversations/my',
  path: '/conversations/my',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: '/chat/$conversationId',
  path: '/chat/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatNewAgentIdRoute = ChatNewAgentIdRouteImport.update({
  id: '/chat/new/$agentId',
  path: '/chat/new/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/auth/reset-password/$token',
  path: '/auth/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackFeedbackIdRoute = AdminFeedbackFeedbackIdRouteImport.update({
  id: '/admin/feedback/$feedbackId',
  path: '/admin/feedback/$feedbackId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/feedback': typeof FeedbackRoute
  '/guide': typeof GuideRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/conversations/my': typeof ConversationsMyRoute
  '/admin/': typeof AdminIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/admin/feedback/$feedbackId': typeof AdminFeedbackFeedbackIdRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/chat/new/$agentId': typeof ChatNewAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/feedback': typeof FeedbackRoute
  '/guide': typeof GuideRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/conversations/my': typeof ConversationsMyRoute
  '/admin': typeof AdminIndexRoute
  '/agents': typeof AgentsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/admin/feedback/$feedbackId': typeof AdminFeedbackFeedbackIdRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/chat/new/$agentId': typeof ChatNewAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/feedback': typeof FeedbackRoute
  '/guide': typeof GuideRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/conversations/my': typeof ConversationsMyRoute
  '/admin/': typeof AdminIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/admin/feedback/$feedbackId': typeof AdminFeedbackFeedbackIdRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/chat/new/$agentId': typeof ChatNewAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/feedback'
    | '/guide'
    | '/settings'
    | '/agents/$agentId'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/chat/$conversationId'
    | '/conversations/my'
    | '/admin/'
    | '/agents/'
    | '/tools/'
    | '/admin/feedback/$feedbackId'
    | '/auth/reset-password/$token'
    | '/chat/new/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/feedback'
    | '/guide'
    | '/settings'
    | '/agents/$agentId'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/chat/$conversationId'
    | '/conversations/my'
    | '/admin'
    | '/agents'
    | '/tools'
    | '/admin/feedback/$feedbackId'
    | '/auth/reset-password/$token'
    | '/chat/new/$agentId'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/feedback'
    | '/guide'
    | '/settings'
    | '/agents/$agentId'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/chat/$conversationId'
    | '/conversations/my'
    | '/admin/'
    | '/agents/'
    | '/tools/'
    | '/admin/feedback/$feedbackId'
    | '/auth/reset-password/$token'
    | '/chat/new/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  FeedbackRoute: typeof FeedbackRoute
  GuideRoute: typeof GuideRoute
  SettingsRoute: typeof SettingsRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ChatConversationIdRoute: typeof ChatConversationIdRoute
  ConversationsMyRoute: typeof ConversationsMyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  AdminFeedbackFeedbackIdRoute: typeof AdminFeedbackFeedbackIdRoute
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
  ChatNewAgentIdRoute: typeof ChatNewAgentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/my': {
      id: '/conversations/my'
      path: '/conversations/my'
      fullPath: '/conversations/my'
      preLoaderRoute: typeof ConversationsMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$conversationId': {
      id: '/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ChatConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/new/$agentId': {
      id: '/chat/new/$agentId'
      path: '/chat/new/$agentId'
      fullPath: '/chat/new/$agentId'
      preLoaderRoute: typeof ChatNewAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/$token': {
      id: '/auth/reset-password/$token'
      path: '/auth/reset-password/$token'
      fullPath: '/auth/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedback/$feedbackId': {
      id: '/admin/feedback/$feedbackId'
      path: '/admin/feedback/$feedbackId'
      fullPath: '/admin/feedback/$feedbackId'
      preLoaderRoute: typeof AdminFeedbackFeedbackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  FeedbackRoute: FeedbackRoute,
  GuideRoute: GuideRoute,
  SettingsRoute: SettingsRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ChatConversationIdRoute: ChatConversationIdRoute,
  ConversationsMyRoute: ConversationsMyRoute,
  AdminIndexRoute: AdminIndexRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  AdminFeedbackFeedbackIdRoute: AdminFeedbackFeedbackIdRoute,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
  ChatNewAgentIdRoute: ChatNewAgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
